### ISSUE TITLE
Cannot use double-conversion via find_package

### ISSUE THREAD

**Issue by dzenanz** [google/double-conversion#100]
I am trying to implement [suggestion](https://github.com/InsightSoftwareConsortium/ITK/issues/579) by @Neumann-A about properly using double-conversion in ITK. My attempt is [here](https://github.com/dzenanz/ITK/commit/a27536c4041780fb4d55831397ae90be5b5cf618).

I cloned `double-conversion` into `C:\Misc\double-conversion\` and built it using VS2017 in `C:\Misc\double-conversion\vs2017\`. If I point `double-conversion_DIR` during ITK configuration to `C:\Misc\double-conversion\vs2017\generated` I get CMake configure error:
```text
CMake Error at C:/Misc/double-conversion/vs2017/generated/double-conversionConfig.cmake:27 (include):
  include could not find load file:

    C:/Misc/double-conversion/vs2017/generated/double-conversionTargets.cmake
Call Stack (most recent call first):
  Modules/ThirdParty/DoubleConversion/CMakeLists.txt:10 (find_package)
```
Rightfully so, because that folder only contains `double-conversionConfig.cmake` and `double-conversionConfigVersion.cmake`.

I then installed `double-conversion` into `C:\Misc\double-conversion\install`, and pointed ITK's `double-conversion_DIR` to `C:\Misc\double-conversion\install\lib\cmake\double-conversion`. This helped somewhat, but now the link library is not defined:
```text
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ITKDoubleConversion_LIBRARIES
    linked by target "ITKCommon" in directory C:/Dev/ITK-git/Modules/Core/Common/src
    linked by target "ITKIOMeshVTK" in directory C:/Dev/ITK-git/Modules/IO/MeshVTK/src
    linked by target "ITKIOTransformInsightLegacy" in directory C:/Dev/ITK-git/Modules/IO/TransformInsightLegacy/src
    linked by target "ITKLabelVotingTestDriver" in directory C:/Dev/ITK-git/Modules/Segmentation/LabelVoting/test
    linked by target "ImageRegionIterator" in directory C:/Dev/ITK-git/Examples/Iterators
    linked by target "NeighborhoodIterators4" in directory C:/Dev/ITK-git/Examples/Iterators
...
```

Using a [script to print all properties of a target](https://stackoverflow.com/a/51987470/276168), I get:
```text
double-conversion::double-conversion ARCHIVE_OUTPUT_DIRECTORY = C:/Dev/ITK-2k17/lib
double-conversion::double-conversion AUTOGEN_ORIGIN_DEPENDS = ON
double-conversion::double-conversion AUTOMOC_COMPILER_PREDEFINES = ON
double-conversion::double-conversion AUTOMOC_MACRO_NAMES = Q_OBJECT;Q_GADGET;Q_NAMESPACE
double-conversion::double-conversion BINARY_DIR = C:/Dev/ITK-2k17/Modules/ThirdParty/DoubleConversion
double-conversion::double-conversion BUILD_WITH_INSTALL_RPATH = OFF
double-conversion::double-conversion CXX_EXTENSIONS = OFF
double-conversion::double-conversion CXX_STANDARD = 11
double-conversion::double-conversion CXX_STANDARD_REQUIRED = ON
double-conversion::double-conversion DEBUG_POSTFIX = 
double-conversion::double-conversion IMPORTED = TRUE
double-conversion::double-conversion IMPORTED_CONFIGURATIONS = DEBUG;RELWITHDEBINFO
double-conversion::double-conversion IMPORTED_GLOBAL = FALSE
double-conversion::double-conversion INSTALL_RPATH = 
double-conversion::double-conversion INSTALL_RPATH_USE_LINK_PATH = OFF
double-conversion::double-conversion INTERFACE_INCLUDE_DIRECTORIES = C:/Misc/double-conversion/install/include
double-conversion::double-conversion LIBRARY_OUTPUT_DIRECTORY = C:/Dev/ITK-2k17/lib
double-conversion::double-conversion NAME = double-conversion::double-conversion
double-conversion::double-conversion POSITION_INDEPENDENT_CODE = ON
double-conversion::double-conversion RUNTIME_OUTPUT_DIRECTORY = C:/Dev/ITK-2k17/bin
double-conversion::double-conversion SKIP_BUILD_RPATH = OFF
double-conversion::double-conversion SOURCE_DIR = C:/Dev/ITK-git/Modules/ThirdParty/DoubleConversion
double-conversion::double-conversion TYPE = STATIC_LIBRARY
```
`INTERFACE_INCLUDE_DIRECTORIES` is correct, but there is no property which points to the library to be linked.

**Do you have a suggestion about how to solve this problem?**

Side question: why don't you support building against build tree? In install tree either debug or release version of the library can be used, which means the other configuration fails to link in Visual Studio, due to:
```text
double-conversion.lib(double-conversion.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in tester.obj
double-conversion.lib(double-conversion.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in tester.obj
```

**Comment by Neumann-A** [comment]
> Do you have a suggestion about how to solve this problem?

After your call to find_package succeeded define:
`set(ITKDoubleConversion_LIBRARIES double-conversion::double-conversion)`
or you have to change every file which tries to link against `ITKDoubleConversion_LIBRARIES`

> INTERFACE_INCLUDE_DIRECTORIES is correct, but there is no property which points to the library to be linked.

That is hidden in the config. You can query the target with `get_target_properties(imp_loc double-conversion::double-conversion IMPORTED_LOCATION_<CONFIG>)`

> In install tree either debug or release version of the library can be used

Copy the targets file manually and call one xxxTargets-release.cmake and xxxTargets-debug.cmake CMake will automatically pick the right one (requires ${_IMPORT_PREFIX} to point to the correct base directory). That is how VCPKG does it.

**Comment by Neumann-A** [comment]
ah it could be that vcpkg manually extracts these information. Can be found in `vcpkg_fixup_cmake_targets`

**Comment by dzenanz** [comment]
`set(ITKDoubleConversion_LIBRARIES double-conversion::double-conversion)` passes configuration step, but generate step throw a lot of errors of the style:
```text
CMake Error at cmake/ITKModuleMacros.cmake:468 (add_library):
  Target "ITKCommon" links to target "double-conversion::double-conversion"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  Modules/Core/Common/src/CMakeLists.txt:179 (itk_module_add_library)

CMake Error at cmake/ITKModuleMacros.cmake:468 (add_library):
  Target "ITKIOMeshVTK" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  Modules/IO/MeshVTK/src/CMakeLists.txt:6 (itk_module_add_library)
```
`IMPORTED_LOCATION_<CONFIG>` and `IMPORTED_LOCATION` didn't help either. But `LOCATION` did! Here is my updated [patch](https://github.com/dzenanz/ITK/commit/2823d9a1ab3f8c0f143535016054be089cf81554), which works for a single configuration (Debug/Release). I guess this will work fine on Linux.

**Comment by Neumann-A** [comment]
>   Target "ITKCommon" links to target "double-conversion::double-conversion"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  Modules/Core/Common/src/CMakeLists.txt:179 (itk_module_add_library)

>CMake Error at cmake/ITKModuleMacros.cmake:468 (add_library):
  Target "ITKIOMeshVTK" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  Modules/IO/MeshVTK/src/CMakeLists.txt:6 (itk_module_add_library)


That means the execution order within your CMakefiles is wrong. 3rd Party libraries must be found first before any non imported add_Library or add_executable call

>updated patch

that is a hack I don't recommend. It won't work if the target defines IMPORTED_LOCATION_<CONFIG>

**Comment by dzenanz** [comment]
ITK's build system was made during the time of CMake 2.8. Rewriting it to use modern target-based syntax is a huge effort, which we are postponing for future. So we cannot link the target properly.
