### ISSUE TITLE
Header-only options?

### ISSUE THREAD

**Issue by ColinH** [google/double-conversion#109]
Before submitting another insane PR I'd like to explain where I'm coming from, and where I'm headed for.

Back in November 2015, when we added this library to our [JSON library](https://github.com/taocpp/json) for double-to-string and string-to-double conversions (because it was the only one that always got string-to-double right), we had to make one big change:

The creation of a header-only version of `Strtod()` (or rather, what is now `StrtodTrimmed()`) by basically copying `Strtod()` into an empty header file and adding everything it depends on (marking functions as `inline` as required) until it worked...

(The code is very "clean" in that it compiles with `-std=c++17 -Wall -Werror -pedantic` even on more modern compilers, kudos!)

Now, in order to allow for easier future updates of the double-conversion part in our JSON library, I wanted to see to which degree it was possible to close the gap between the current form, and the partial header-only form that we would require.

(Where "possible" is to be understood both in terms of technically possible, and in line with your development style and plans for the future.)

So what I'd _like_ to do, if _possible_, is eliminate all `*.cc` files except for `string-to-double.cc` and `double-to-string.cc` by moving everything into the respective `*.h` files, making sure everything is marked as `inline`. Then some `*.h` files could be split up, e.g. by moving `StringBuilder` into a dedicated file etc. Finally the namespace could become a macro to make changing it easier.

Then we could simply copy `strtod.h`, and all other headers it depends on, and take it from there. Now we realise that's probably a rather non-standard use-case, which is why I wanted to check in first and see whether this would be ok with you...

Final note, in case you are wondering what the commits I have submitted so far have to do with creating a partial header-only version of this library, the answer is that I simply wanted to (re)acquaint myself a bit more with the code, and understanding enough to make _some_ contributions (in the direction of more idiomatic "modern" C++, or some small simplifications) is one way I use to get to know a piece code.

Thank you for listening, hope I'm not taking too much of your time ;-)

**Comment by floitsch** [comment]
I thought a bit about this, but I don't think that change is really worth it.
A header-only version feels very alien to me and wouldn't hit many use-cases.
Since the library isn't changing a lot, it shouldn't be too hard to keep your header-only version up to date.

> Thank you for listening, hope I'm not taking too much of your time ;-)
No worries. Great to see contributions :)

**Comment by ColinH** [comment]
Fair enough, and with the changes that you accepted the gap is smaller than it used to be, it won't be a problem for us.
