### ISSUE TITLE
Unexpected behavior with subnormal doubles

### ISSUE THREAD

**Issue by sffc** [google/double-conversion#126]
If I try to convert DBL_TRUE_MIN, which has numeric value 4.9E-324, I get 5E-324 instead of 4.9E-24.  Example code:

```cpp
#ifndef DBL_TRUE_MIN
#define DBL_TRUE_MIN 4.9E-324
#endif

int main() {
    char buffer[DoubleToStringConverter::kBase10MaximalLength + 1] = {};
    bool sign; // unused; always positive
    int32_t length;
    int32_t point;
    DoubleToStringConverter::DoubleToAscii(
        DBL_TRUE_MIN,
        DoubleToStringConverter::DtoaMode::SHORTEST,
        0,
        buffer,
        sizeof(buffer),
        &sign,
        &length,
        &point
    );
    std::cout << buffer << std::endl;
}
```

Downstream issue: https://unicode-org.atlassian.net/browse/ICU-20974

**Comment by orivej** [comment]
`4.9E-324 == 5E-324` is true, and "5E-324" is shorter, so it is a better (and in fact correct) shortest string representation of DBL_TRUE_MIN (which is exactly 2^-1074 rather than 4.9*10^-324).

**Comment by sffc** [comment]
Java Double.toString(Double.MIN_VALUE) returns `4.9E-324`, so this is an inconsistency in behavior.  In all other situations I've seen, double-conversion agrees with Java Double.toString().

**Comment by orivej** [comment]
Java [ensures](https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#toString-double-) that the first digit is equal to the first significant digit of the precise decimal representation, and also that there is at least one digit after `.`, while DtoaMode::SHORTEST ensures that the printed representation is the shortest possible that encodes this double. This makes them differ in such cases as 1e7 (toDouble gives "1.0E7") and 1e23 (toDouble gives "9.999999999999999E22", as reported [here](https://bugs.openjdk.java.net/browse/JDK-4511638), decided as working as intended).

**Comment by floitsch** [comment]
Thanks @orivej for the fast responses and the references.
There is currently no plan to implement Java's behavior in the library.
