### ISSUE TITLE
Don't use __has_attribute on MSVC

### ISSUE THREAD

**Issue by sffc** [google/double-conversion#129]
The following line was recently added to utils.h:

```cpp
#if defined(__clang__) && __has_attribute(uninitialized)
```

This is causing compiler warnings on MSVC.  @jefgen had some ideas on how to fix this.

Additional context:

https://github.com/unicode-org/icu/pull/1076#discussion_r401179824

**Comment by jefgen** [comment]
Thanks for filing this!
