### ISSUE TITLE
StringToDouble: 2.64x speed-up possible via Eisel algorithm

### ISSUE THREAD

**Issue by nigeltao** [google/double-conversion#137]
https://lemire.me/blog/2020/03/10/fast-float-parsing-in-practice/ briefly describes a new StringToDouble algorithm by Michael Eisel. It claims a 2.64x speed-up versus this library, `github.com/google/double-conversion`.

The `github.com/google/wuffs` repo contains a re-implementation of that Eisel algorithm:
- The core code is https://github.com/google/wuffs/blob/229a0c5af42a60e466aa3e3dcd82fb8f733b6a83/internal/cgen/base/floatconv-submodule-code.c#L833-L991
- The core data table is https://github.com/google/wuffs/blob/229a0c5af42a60e466aa3e3dcd82fb8f733b6a83/internal/cgen/base/floatconv-submodule-data.c#L157 which is a more detailed version of this repo's `kCachedPowers` table at https://github.com/google/double-conversion/blob/b1d531bfb130e7149ffe24bb0f1c5c01f20c3a5f/double-conversion/cached-powers.cc#L46

https://crrev.com/c/2291558/11 is an experimental change to the Chromium web browser to use Wuffs' Eisel implementation instead of `google/double-conversion`. Parsing various JSON files sped up by between 1.01x and 1.46x. That's the total time to parse a JSON file (and allocate the resultant node tree), not just the net time spent in `StringToDouble` or its equivalent. Obviously, the speed-up is more dramatic for number-ful JSON (as opposed to string-ful JSON).

Perhaps this library should consider adopting the same algorithm.

**Comment by floitsch** [comment]
The string->double conversion was never optimized in this library. It should have a decent speed, but there are definitely low hanging fruits.
Unfortunately, I currently don't have time to improve the library (as long as it yields the correct results).
For example, the library could/should also switch to Ryu (https://github.com/ulfjack/ryu) which should make it faster and avoid the pesky corner cases described in #83.

Closing, to avoid giving the impression that someone is working on it.
If I find the time to work on it, I will reopen.
