### ISSUE TITLE
kMaxFixedDigitsAfterPoint should be increased from 60 to 100

### ISSUE THREAD

**Issue by jandem** [google/double-conversion#152]
This week I [switched](https://bugzilla.mozilla.org/show_bug.cgi?id=944846#c20) SpiderMonkey's implementation of `Number.prototype.{toExponential, toPrecision, toFixed}` from dtoa to double-conversion.

The main issue we ran into is that for `toFixed`, JS implementations need to support up to 100 digits after the point (see [spec](https://tc39.es/ecma262/#sec-number.prototype.tofixed), step 5), so I had to change `kMaxFixedDigitsAfterPoint` from 60 to 100 in our copy.

The spec used to require a smaller range (0-20 IIRC) here and left the rest as an implementation choice, but that changed at some point.

**Comment by floitsch** [comment]
Why would they do that?
But ok. I will have a look and see if it can be done easily.

**Comment by jandem** [comment]
Thanks for the ultra quick response! I filed this as first step towards upstreaming a patch, but if you can take a look yourself that would be even better :)
