### ISSUE TITLE
`StringToDoubleConverter::StringTo<FloatingPoint>` member function templates

### ISSUE THREAD

**Issue by N-Dekker** [google/double-conversion#157]
It would appear very helpful to me to have `StringToDoubleConverter::StringTo<FloatingPoint>` member function templates, allowing to call

    converter.StringTo<FloatingPoint>(buffer, length, processed_characters_count);

For either `double` or `float` as `FloatingPoint` template argument. It should behave just like the corresponding (existing) non-template member function, which is either one of the corresponding `StringToDouble` or `StringToFloat` overloads.  

This member function templates would make it easier for users to write generic code at the client side. (As I personally experienced while preparing pull request https://github.com/SuperElastix/elastix/pull/455 "BUG: Use double-conversion instead of std::istringstream in ParameterMap" for the [elastix](https://github.com/SuperElastix/elastix) project I'm involved with.)

A draft implementation of these member function templates is at https://github.com/N-Dekker/double-conversion/tree/StringToDoubleConverter-StringTo-template Should I make it a pull request?

**Comment by floitsch** [comment]
I think that would be ok.
since I already skimmed the branch you created:
- I prefer `typename` in the template: `template <typename FloatingPoint>`.
- I usually use a one-character name for template arguments, but that's not something I will enforce.
- would need at least some tests.

**Comment by N-Dekker** [comment]
@floitsch  Thanks for your quick and encouraging response, Florian! In general I also prefer `typename` in template declarations. I was just trying to be consistent with the existing `template <class Iterator>`, in the very same header file. But now I see, "double-conversion/utils.h" has `template <typename T>`. I will amend my commit accordingly before submitting the PR. 

Also I'll try to add some tests to "test-conversions.cc". Looks like that's the proper place, right?

**Comment by floitsch** [comment]
Yes. test-conversions looks good.
