### ISSUE TITLE
[bug] ieee.h: Wrong QuietNaN bit check on mips* architectures

### ISSUE THREAD

**Issue by cdluminate** [google/double-conversion#171]
double-conversion `3.1.7` has introduced some quiet_nan bit checks for the `Single` and `Double` classes defined in `double-conversion/ieee.h`. But the code failed to pass the test on the mips* architectures according to Debian buildlogs: https://buildd.debian.org/status/package.php?p=double%2dconversion

According to wikipedia, https://en.wikipedia.org/wiki/NaN, the mips* architecture regard the `is_quiet/is_signaling` bit the reversed way compared to other architectures. Thus we have to flip the logic in the corresponding new code. I've written a preliminary patch against this bug: https://salsa.debian.org/science-team/double-conversion/-/blob/lumin/debian/patches/fix-mips.patch

I'll submit it as a patch when I finished tests.

**Comment by floitsch** [comment]
Thanks for the report.

Looking forward to the patch.
