### ISSUE TITLE
Kindly add installation of Windows debugger files (pdb)?

### ISSUE THREAD

**Issue by emmenlau** [google/double-conversion#173]
Thanks for this great library!

I've seen that when built on Windows, it generates debugger information (in file `double-conversion.pdb`). However this file is not installed with `make install`. Therefore it can not be found during debugging, and i.e. it is lost when the build tree is removed.

Would it be possible to add this file to the install target on Windows? I guess something like this may be a good start for shared library builds:
```
install(
    FILES $<TARGET_PDB_FILE:double-conversion>
    DESTINATION "${CMAKE_INSTALL_BINDIR}"
    OPTIONAL
)
```

It works a bit different for static libraries, though. See https://stackoverflow.com/a/40860436/7200132 for a good discussion.

**Comment by emmenlau** [comment]
I just wanted to add that its also possible to generate and store `pdb` files for static library builds. However requires that the `COMPILE_PDB_NAME` is set in cmake for the target. So something along those lines would need to be added in addition to the install command from above, too:
```
if (MSVC AND NOT BUILD_SHARED_LIBS)
    # Set the output name for debugger files, otherwise they are not generated:
    set_target_properties(${PROJECT_NAME}
        PROPERTIES
        COMPILE_PDB_NAME_DEBUG ${PROJECT_NAME}
        COMPILE_PDB_NAME_RELEASE ${PROJECT_NAME}
        COMPILE_PDB_NAME_MINSIZEREL ${PROJECT_NAME}
        COMPILE_PDB_NAME_RELWITHDEBINFO ${PROJECT_NAME})
endif()
```
Then the install command should work for the static and the shared case.

PS: I'm assuming here that the library target is called `${PROJECT_NAME}`. Otherwise please replace this with the library target(s).

**Comment by floitsch** [comment]
Thanks. I will try to have a look in the next few days.
Don't hesitate to ping if you don't see anything within a week or so.

**Comment by emmenlau** [comment]
Thanks a lot @floitsch ! There is also a related discussion at https://github.com/open-mpi/hwloc/issues/512 that has progressed a bit into how to PDB install could work for static and shared libraries...

**Comment by floitsch** [comment]
I ended up only installing pdb files for shared libs.
I'm not using Windows, and not familiar enough for more.

At least I added more Windows buildbot tests.

**Comment by emmenlau** [comment]
Thanks a lot, its appreciated!
