### ISSUE TITLE
FastFixedDtoa incorrect rounding.

### ISSUE THREAD

**Issue by isliser** [google/double-conversion#183]
I've encountered a rounding problem using FastFixedDtoa in some Halfway cases. For example 0.15 with precision=2 is rounded to 0.1, whereas it's expected to be equal 0.2. I suppose this happens due to the fact that 0.15 internally is represented as 0.14999999999999999. 
Would you fix it or suggest any workaround?

Sample to reproduce the problem
```
#include <array>
#include <iostream>

#include <double-conversion/fixed-dtoa.h>

int main()
{
    int length;
    int point;

    std::array<char, 512> buffer;

    double value = 0.15;

    double_conversion::FastFixedDtoa(value, 1, {buffer.data(), buffer.size()}, &length, &point);

    std::cout << "length=" << length << std::endl;
    std::cout << "point=" << point << std::endl;
    std::cout << "string='" << std::string(buffer.data(), length) << "'" << std::endl;

    return 0;
}

```

**Comment by floitsch** [comment]
You are correct:
The internal value of 0.15 is ~0.14999999999999999445 and rounding to just one precision values thus gives 0.1.

This is, what many specifications require (like the JavaScript or Dart specification), and we can't (and don't want to) change the library for that.

You also have to think of it from the opposite direction: if a user writes:
```
  double value = 0.14999999999999999999999;
  double_conversion::FastFixedDtoa(value, 1, {buffer.data(), buffer.size()}, &length, &point);
```
then it would be surprising, if the result is 2.

If you want to always work from the shortest string representation you could just convert the number to a string first, and then chop off the characters you don't want/need.
