### ISSUE TITLE
Various warnings compiling with visual studio

### ISSUE THREAD

**Issue by Ono-Sendai** [google/double-conversion#187]
`1>double-conversion\bignum.cc(243,30): warning C4244: '+=': conversion from 'int' to 'int16_t', possible loss of data
1>double-conversion\bignum.cc(421,18): warning C4244: '=': conversion from 'const int' to 'int16_t', possible loss of data
1>double-conversion\bignum.cc(742,21): warning C4244: '+=': conversion from 'const int' to 'int16_t', possible loss of data
1>double-conversion\bignum.cc(743,18): warning C4244: '-=': conversion from 'const int' to 'int16_t', possible loss of data`

etc.

**Comment by floitsch** [comment]
I don't have any Windows machine, but I will see if I can fix these warnings.
Feel free to ping me if nothing is happening.
