### ISSUE TITLE
Hash Pin Github Owned Actions

### ISSUE THREAD

**Issue by joycebrum** [google/double-conversion#197]
## Description

I would like to suggest another security practice recommended by the [OpenSSF Scorecard][scorecard-repo] which is to hash pin dependencies to prevent typosquatting and tag renaming attacks. 

The change would only be applied to GitHub workflows. This means hash pinning GitHub Workflow actions.

Although only Github Owned Actions are used (which are considered trustful) they still are open source projects and can be compromised just as any open source project could. 

I can submit one PR for each type of change above to be easier to review if you prefer. Just let me know if that's the case.

Along with hash-pinning dependencies, I also recommend adopting dependabot or renovatebot to help keep the dependencies up to date. Both tools can update  hashes and associated semantic version comments. 

Together with this issue I'll also suggest a PR with the changes since they are quite simple. 

Any questions or concerns just let me know.
Thanks!

## Additional Context

A tag renaming attack is a type of attack whereby an attacker:
- Hijack an action.
- Upload a malicious version.
- Replace existing tags with malicious versions.

 
A [typosquatting attack][typosquatting] is a type of attack whereby an attacker:
- Create a malicious package
- Publish it with a similar name of a known package (example: numpi instead of numpy)

For more informations about the dependency-update tools:
- [Dependabot][dependabot]
- [Renovatebot][renovatebot]

[scorecard-repo]: https://github.com/ossf/scorecard
[deps-confusion]: https://www.websecuritylens.org/how-dependency-confusion-attack-works-and-how-to-prevent-it/ 
[typosquatting]: https://snyk.io/blog/typosquatting-attacks/ 
[dependabot]: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
[renovatebot]:https://www.mend.io/renovate/

**Comment by joycebrum** [comment]
Let me know if you are interested in either trying dependabot or renovatebot and I can help with suggesting a standard configuration file.

**Comment by floitsch** [comment]
Except for Github actions there shouldn't be any dependencies, but if you have suggestions on how to add dependabot/renovatebot I would be happy to have a look.

Also: do you have a script that updates the git hash in workflow files? Our other workflow files are currently using version-tags, and replacing them with hashes feels like too much work if it's not automated...

**Comment by joycebrum** [comment]
You can try using the [Step Security](https://www.stepsecurity.io/) to help on hash pinning. Example: https://app.stepsecurity.io/secureworkflow/google/nomulus/codeql.yml/master?enable=pin

About dependabot, I'll submit a config file to only update the workflow files and instructions to enable it on config!
