### ISSUE TITLE
question: does abseil-cpp cover double-conversion functionality

### ISSUE THREAD

**Issue by romange** [google/double-conversion#213]
Specifically, does it use efficient algorithms to convert double to strings?

**Comment by floitsch** [comment]
I'm pretty sure it doesn't: https://github.com/abseil/abseil-cpp/blob/fc44fa053cc91193d2bb60fb9356bcecb301242e/absl/strings/internal/str_format/float_conversion.cc#L209

I think the library has some shortcuts for simple numbers, but the generic case looks like it's not optimized.
