### ISSUE TITLE
fatal: unable to access 'https://github.com/google/double-conversion.git/': CONNECT tunnel failed, response 403

### ISSUE THREAD

**Issue by KiranKumarRDA** [google/double-conversion#222]
Installing DoubleConversion (1.1.6)

[!] Error installing DoubleConversion
[!] /usr/bin/git clone https://github.com/google/double-conversion.git /var/folders/9q/rrg068vn3xdbbpqfsqhd0gkw0000gp/T/d20240321-51504-egyfmm --template= --single-branch --depth 1 --branch v1.1.6

Cloning into '/var/folders/9q/rrg068vn3xdbbpqfsqhd0gkw0000gp/T/d20240321-51504-egyfmm'...
fatal: unable to access 'https://github.com/google/double-conversion.git/': CONNECT tunnel failed, response 403

**Comment by floitsch** [comment]
I can't reproduce.
This looks like an issue on your end.

GitHub did not report any incident recently, and the error code 403 indicates that it could be a firewall or similar that is preventing you from contacting GitHub.
