### ISSUE TITLE
cmake not building with fPIC

### ISSUE THREAD

**Issue by chadrik** [google/double-conversion#34]
scons adds -fPIC but cmake does not. 

Adding this to double-conversion/src/CMakeLists.txt solved my problem:

```
if (CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
  set_target_properties(double-conversion PROPERTIES COMPILE_FLAGS "-fPIC")
endif()
```

**Comment by floitsch** [comment]
Sounds good to me.
@Chaircrusher wrote the CMake files. Unless he has an objection I will add this line.

**Comment by Chaircrusher** [comment]
No objection.  One thing: it wouldn't hurt to check to make sure that's a valid compiler flag. The following would make sure that the flag occurs; there may be other PIC flags that would work e.g. with Windows compilers.
`
include(CheckCXXCompilerFlag)
check_cxx_compiler_flag(-fPIC CXX_HAS_FPIC)
if(CXX_HAS_FPIC AND CMAKE_SYSTEM_PROCESSER STREQUAL "x86_64")
  set_target_properties(double-conversion PROPERTIES COMPILE_FLAGS "-fPIC")
endif()
`

**Comment by floitsch** [comment]
Sorry this is always taking so long...
I uploaded a PR to add support for the flag. If you don't have any objections I will merge this PR soon.

**Comment by chadrik** [comment]
looks good to me.
