### ISSUE TITLE
Undefined behavior 

### ISSUE THREAD

**Issue by cschnei3** [google/double-conversion#35]
line 456:  ~((static_cast<uint64_t>(1) << (64 - bit_size)) - 1);
Is undefined behavior, since 64-bit_size could be negative. 

From http://open-std.org/JTC1/SC22/WG21/docs/papers/2016/n4594.pdf: 
The value of E1 << E2 is E1 left-shifted E2 bit positions; vacated bits are zero-filled. If E1 has an unsigned
type, the value of the result is E1 × 2
E2, reduced modulo one more than the maximum value representable in
the result type. Otherwise, if E1 has a signed type and non-negative value, and E1 × 2
E2 is representable
in the corresponding unsigned type of the result type, then that value, converted to the result type, is the
resulting value; otherwise, the behavior is undefined.
3 The value of E1 >> E2 is E1 right-shifted E2 bit positive

**Comment by mihaipopescu** [comment]
When can `bit_size > 64`  ? That doesn't seem possible https://github.com/google/double-conversion/blob/56a04575a474b929a4aa4fb72d83d46c8a93f294/double-conversion/bignum.cc#L428

**Comment by floitsch** [comment]
I agree with @mihaipopescu: the bit_size is the bit size of the incoming `base` which is a `uint16_t`. The value of `bit_size` can thus never exceed 16.
