### ISSUE TITLE
UB in FastFixedDtoa

### ISSUE THREAD

**Issue by effzeh** [google/double-conversion#41]
The following test cases all result in a negative shift count (-1) in FillFractionals [here](https://github.com/google/double-conversion/blob/master/double-conversion/fixed-dtoa.cc#L262)

    FastFixedDtoa( 2.10861548515811875e+15, 17, buffer, &length, &point );
    FastFixedDtoa( 2.64452047982146350e+15, 17, buffer, &length, &point );
    FastFixedDtoa( 3.82353004488187350e+15, 17, buffer, &length, &point );
    FastFixedDtoa( 2.33131995055488594e+14, 17, buffer, &length, &point );
    FastFixedDtoa( 1.91674615419831375e+15, 17, buffer, &length, &point );
    FastFixedDtoa( 4.29987917825301050e+15, 17, buffer, &length, &point );
    FastFixedDtoa( 8.57854524678346875e+14, 17, buffer, &length, &point );
    FastFixedDtoa( 3.88706467562864350e+15, 17, buffer, &length, &point );
    FastFixedDtoa( 1.54620738641213675e+15, 17, buffer, &length, &point );
    FastFixedDtoa( 1.90564594624582575e+15, 17, buffer, &length, &point );
    FastFixedDtoa( 1.47829189951993075e+15, 17, buffer, &length, &point );
    FastFixedDtoa( 3.40787290971543450e+15, 17, buffer, &length, &point );

(When the test is performed, in all of these cases `fractionals = 0` and `point = 0`.)

**Comment by floitsch** [comment]
Fixed and thanks.
