### ISSUE TITLE
Google/double-conversion

### ISSUE THREAD

**Issue by ggconsz** [google/double-conversion#43]
I'm neeewb how the shit does this work

**Comment by floitschG** [comment]
You first need to compile the library and link it into your project. The project comes with support for the build systems "scons" and "cmake". You should be able to find many tutorials on how to use those.

If you need a C interface, you will have to write a wrapper for the library. Again, there are many tutorials on the web for this. Depending on what exactly you need, you could also try to reuse the code that was used to benchmark when I wrote the paper (see below): http://florian.loitsch.com/publications/bench.tar.gz

Once you can compile the project and link it to your project, you want to look at https://github.com/google/double-conversion/blob/master/double-conversion/double-conversion.h. This file contains all the methods you need. For simplicity, you might want to start with the `EcmaScriptConverter` which is exposed there. It provides the same conventions as JavaScript.

If you want to know, how exactly the conversion is happening, there is a paper here: http://florian.loitsch.com/publications/dtoa-pldi2010.pdf

Hope that helps.
