### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by ghisvail** [google/double-conversion#45]
The last tagged release is dated from 2014 and quite a few fixes have landed in the code base since then. Would you guys consider tagging a new release with the appropriate version bump?

Cheers,

**Comment by floitsch** [comment]
Sorry for the delay (vacations).

I just tagged new releases.

Since the source code has changed in incompatible ways I bumped the major version number instead of tagging another 2.x release.

I'm not used to doing releases. If I missed something please reopen the issue.
