### ISSUE TITLE
Add support for a separator character

### ISSUE THREAD

**Issue by Anteru** [google/double-conversion#49]
Another issue not strictly related to JavaScript, would be nice to see support for a configurable separator character. It's ok if it's a single character, this way numbers like 1_000_000 and 1'000'000 could be parsed without having to pre-process them.

**Comment by floitschG** [comment]
I agree.
I don't have lots of time right now, though.
Please ping from time to time. Maybe I can find some time in the future.

**Comment by Anteru** [comment]
Pinging you, hoping we're in the future you wrote about now.

**Comment by Anteru** [comment]
Thanks a lot!
