### ISSUE TITLE
The spec.prepare_command lead an error

### ISSUE THREAD

**Issue by FlyingNoob** [google/double-conversion#55]
When I use reactnative Integration in an with Existing Apps. I get an error .
```
nstalling DoubleConversion (1.1.5)
[!] /bin/bash -c
set -e
mv src double-conversion

mv: rename src to double-conversion: No such file or directory
```

**Comment by floitschG** [comment]
The script for reactnative still uses a layout from a previous version.
You can work around this in 3 ways:
1. mv the `double-conversion` directory (the one that contains all the sources: https://github.com/google/double-conversion/tree/master/double-conversion) to `src` before calling the installation script.
2. use an older version of the library. (There weren't any significant changes).
3. change the script to *not* do the `mv`.

**Comment by temitope** [comment]
@FlyingNoob I ran into the same issue. Did you find a fix. @floitsch suggestions did not work for me.

**Comment by rob-keepsafe** [comment]
@temitope See another solution here https://github.com/facebook/react-native/issues/16460
