### ISSUE TITLE
clang -Wunused-template warnings on Min & Max

### ISSUE THREAD

**Issue by seanm** [google/double-conversion#56]
clang give 2 warnings:

```
utils.h:166:10: warning: unused function template 'Max' [-Wunused-template]
static T Max(T a, T b) {
         ^
utils.h:173:10: warning: unused function template 'Min' [-Wunused-template]
static T Min(T a, T b) {
         ^
```

I suspect it has to do with the 'static' declaration...

**Comment by floitschG** [comment]
Not yet sure what to do there.

They are marked `static` so that they aren't exported (which sounds correct to me).
In some files they won't be used (which also sounds good to me).

**Comment by floitsch** [comment]
Had another look at this.
I don't see any good way of avoiding this without duplicating code.
Therefore closing this issue.
