### ISSUE TITLE
support for multiple inf/nan styles

### ISSUE THREAD

**Issue by ahrvoje** [google/double-conversion#58]
I tested the routines on Win10 VS2017 against [my strtod test battery](https://github.com/ahrvoje/numerics/blob/master/strtod/strtod_tests.toml) and all conversion tests passed. This is a very good sign!

Nevertheless some formatting tests failed due to the fact multiple styles for `inf` & `nan` literals aren't supported, e.g. excepting both `'inf'` & `'infinity'` just as Python does.

It would be nice to be able to construct `StringToDoubleConverter` which is able to interpret multiple style as described in C99 standard section 7.19.6.1.8.

Maybe one way to do this is to be able to use regex for `StringToDoubleConverter` `infinity_symbol` & `nan_symbol`.

**Comment by floitsch** [comment]
I would prefer not to modify the API.

It's probably simpler to wrap the calls and check for the second `inf` (or `nan`) yourself:

``` c
double Parse(const char* buffer, int length) {
  // Assumes, that `stringToDoubleConverter` accepts `"infinity"`.
  int processed;
  double result = stringToDoubleConverter.StringToDouble(buffer, length, &processed);
  if (processed == 0) {
    // Could still be "inf".
    // TODO: check for negative infinity, and trim the whitespaces.
    if (length == 3 && strcmp(buffer, "inf") == 0) return 1.0 / 0.0.
  }
  return result;
}
```

There is a bit of redundant work for the whitespaces.
Since these cases should be relatively rare, you could also just instantiate two different converters:
``` c
double Parse(const char* buffer, int length) {
  // Assumes, that `stringToDoubleConverter` accepts `"infinity"`.
  int processed;
  double result = stringToDoubleConverter.StringToDouble(buffer, length, &processed);
  if (processed == 0) {
    result = stringToDoubleConverterShortInf.StringToDouble(buffer, length, &processed);
  }
  return result;
}
```

**Comment by ahrvoje** [comment]
Wrapping would require reimplementing a lot of nice features the lib has (e.g. spaces after sign...) Also defining two converters is not sufficient due to a fact that there are more combinations to consider not only two 'inf' strings (e.g. various NaN strings), the approach isn't practical the moment you have more than two cases to check for.

I recommend introducing StringToDoubleConverterR which accepts Regex for 'inf' & 'nan' strings.

**Comment by floitsch** [comment]
I will see if we can expose the `trim` functionality.
This way, the test for additional strings would really become simple.
I would really prefer not to depend on a regexp package.
