### ISSUE TITLE
Support Windows on ARM

### ISSUE THREAD

**Issue by KindDragon** [google/double-conversion#60]
You can use define `_M_ARM` for that

See https://github.com/Microsoft/vcpkg/pull/1167

**Comment by floitsch** [comment]
Could you please verify that the uploaded PR works on Windows ARM machines.
Thanks.

**Comment by KindDragon** [comment]
I do not have an ARM machine, but @zabulus checked VCPKG build and it works for him

**Comment by KindDragon** [comment]
Fixed in #76
