### ISSUE TITLE
Minimal test file example

### ISSUE THREAD

**Issue by xmnlab** [google/double-conversion#70]
Hi everyone!

I am packaging double-conversion using conda-build (https://github.com/conda-forge/staged-recipes/pull/5770)

I need to add a very small test file to check if double-conversion is installed properly.

Could you point me a very simple test file and an example about how could I use it?

My best regards,

**Comment by floitsch** [comment]
All tests are in the test directory.
(`make test` would run the tests)

You can also build your own test. I would look at
https://github.com/google/double-conversion/blob/master/test/cctest/test-dtoa.cc#L50
and run it with some of the various doubles (line 81 in the same file).

Hope that helps.

**Comment by xmnlab** [comment]
Thanks a lot!
