### ISSUE TITLE
Last digit not rounded even in PRECISION mode

### ISSUE THREAD

**Issue by tbkka** [google/double-conversion#72]
When using `double_conversion::DoubleToStringConverter::DoubleToAscii()` with `mode=PRECISION` and `requested_digits=6`, I find that the input 5735285 generates digits 573529.

I believe it should be 573528 (with the last digit rounded even), as produced by David M. Gay's `dtoa` with mode 2.

**Comment by floitsch** [comment]
Looked at it today.

I agree that "round-to-even" is generally used when converting from decimal to binary.
For the other direction, there doesn't seem to be a similar convention, and comments in the code explicitly state:
```
Remainders of exactly .5 round upwards.
```
(comment in `GenerateCountedDigits`).

Changing the output now would be a breaking change. Unless there is a good reason I would keep the code the way it is.
(There are already other changes compared to Gay where `dtoa` produced non-optimal results, so users switching from Gay to this library need to be aware of minor changes anyway).
