### ISSUE TITLE
Support for Microblaze and OpenRISC ?

### ISSUE THREAD

**Issue by tpetazzoni** [google/double-conversion#73]
Buildroot is building Qt5 for a large number of architectures, and the build now fails on Microblaze and OpenRISC architecture because the copy of the double-conversion library in Qt5 doesn't have support for those architecture.

I am willing to test on those architectures what needs to be tested, but unfortunately the comment at https://github.com/google/double-conversion/blob/master/double-conversion/utils.h#L60 is not clear enough (to me) to know what to test.

Also, wouldn't it make sense for the code in utils.h to assume that DOUBLE_CONVERSION_CORRECT_DOUBLE_OPERATIONS is false for unsupported/unknown architectures ?

**Comment by floitsch** [comment]
I will see if setting the default to false always works.

In the meantime, here is how to test it (from memory):
Create two files and compile them separately:
```
// div.c
double Div_double(double x, double y) { return x / y; }
```
```
// main.c
double Div_double(double x, double y);

int main(int argc, char** argv) {
  return Div_double(89255.0, 1e22) == 89255e-22;
}
```
Compile them separately and link the o-files.
`./main || echo "correct"` should now tell you whether the conversion is correct.

If you get "correct" as result, we can just add the new architectures to the list. (Ideally after you ran the tests).

**Comment by pseiderer** [comment]
Added double-conversion support for the Qt5 (bundled double-converison library) buildroot cross-compile (aarch64_be [1], or1k [2][3], microblazeel/microblazebe [4]) lately, see the links for the
corresponding architecture defines and (qemu only) Div_double tests...

[1] http://lists.busybox.net/pipermail/buildroot/2018-August/227675.html
[2] http://lists.busybox.net/pipermail/buildroot/2018-August/228151.html
[3] http://lists.busybox.net/pipermail/buildroot/2018-August/228150.html
[4] http://lists.busybox.net/pipermail/buildroot/2018-August/228543.html

**Comment by floitsch** [comment]
Thanks.
I updated the header.
Note that the file had already changed, and that your (@pseiderer ) patches will now be conflicting.
