### ISSUE TITLE
Consider switching to the Ryū algorithm for float to string conversions

### ISSUE THREAD

**Issue by SiggyBar** [google/double-conversion#74]
https://github.com/ulfjack/ryu
https://www.reddit.com/r/programming/comments/92dncd/ry%C5%AB_fast_floattostring_conversion/

On my laptop I quickly measured Ryū to almost be 4X faster than double-conversion.

The implementation in the GitHub repository above lacks the output format flexibility offered by double-conversion, so that would need to be addressed.

**Comment by floitsch** [comment]
I won't have the time to implement or port Ryu.
It would probably be a better idea to port double-conversion's API to Ryu instead. Consider filing a bug-report there.
