### ISSUE TITLE
CMake build produces "libdouble-conversion.so.3.0.0" as the soname

### ISSUE THREAD

**Issue by thiagomacieira** [google/double-conversion#77]
This indicates a binary-incompatible change, but there doesn't seem to be the need for one. It seems to me that commit e13e72e1 incorrectly changed the way the soname is created (which wasn't being done properly in 2.0 either, but that's another story).

**Comment by floitsch** [comment]
Thanks.
I believe things are correct now. (Tbh, I completely forget about versioning. I hope it didn't screw up too many distributions/projects).
