### ISSUE TITLE
Support installing into /usr/lib64

### ISSUE THREAD

**Issue by opoplawski** [google/double-conversion#8]
On Fedora, 64-libraries need to get installed into /usr/lib64.

**Comment by opoplawski** [comment]
The installed cmake files would need to go there as well.  Also, the convention on Fedora at least is to use /usr/lib{,64}/cmake instead of /usr/lib/CMake.

**Comment by floitsch** [comment]
Sorry for the late reply (didn't see the notification).
Is there an easy way to make this happen, while still keeping compatibility with other distributions?

**Comment by opoplawski** [comment]
You have a couple options - you can make use of the GNUInstallDirs cmake module or you could accept something like a -DLIB_SUFFIX=64 option and set it empty by default.

**Comment by heirecka** [comment]
https://github.com/google/double-conversion/pull/29 allows passing a custom libdir

**Comment by floitschG** [comment]
Fixed with a1ee96d5ada476a0ea7a6ce7149c40f60f6f1eb8.
Sorry for the lack of response, and thanks again to @heirecka.
