### ISSUE TITLE
Conan Package

### ISSUE THREAD

**Issue by uilianries** [google/double-conversion#80]
Hello,

Do you know about [Conan](https://conan.io)?

Conan is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

Now we have famous C++ projects, including Google Flatbuffers. We could support you writing a recipe and publishing your packages on [Bintray](https://bintray.com/conan/conan-center).

If you have any questions, just ask :-)

**Comment by floitsch** [comment]
Sorry for the late reply.
I have barely the time to do crucial maintenance work on this library, and it is highly unlikely that I will find the time to write a package description.

**Comment by uilianries** [comment]
Understood, thanks for you reply.

Anyway, [Bincrafters](https://bincrafters.github.io/) already offers a package for double-conversion:

https://github.com/bincrafters/conan-double-conversion
https://bintray.com/bincrafters/public-conan/double-conversion%3Abincrafters 

Feel free to try or comment.
Regards!
