### ISSUE TITLE
Update from 3.0 to 3.1 breaks vcpkg build

### ISSUE THREAD

**Issue by dzenanz** [google/double-conversion#85]
`C:\src\vcpkg\installed\x64-windows\include\double-conversion\double-conversion.h(31): fatal error C1083: Cannot open include file: 'double-conversion/utils.h': No such file or directory` is the error encountered. More information can be found in vcpkg's [issue](https://github.com/Microsoft/vcpkg/issues/4334).

**Comment by dzenanz** [comment]
The same thing happens on [Linux](https://discourse.itk.org/t/double-conversion-problem-in-vcpkg-build/1486/3?u=dzenanz). What I think is wrong, is that `double-conversion.h` thinks its containing folder's parent will be in the include path, and that it can reference it via `double-conversion/utils.h`. I think that just `utils.h` would work [better].

The include paths provided is `C:\Dev\vcpkg\installed\x64-windows-static\include\double-conversion`, but `C:\Dev\vcpkg\installed\x64-windows-static\include` is not. See my [post](https://discourse.itk.org/t/double-conversion-problem-in-vcpkg-build/1486?u=dzenanz).

**Comment by phcerdan** [comment]
I just had a quick look, and seems related to missing the target include directory for the install tree?

https://github.com/google/double-conversion/blob/master/CMakeLists.txt#L27

**Comment by floitsch** [comment]
I'm sorry I still haven't found the time to look at this. It's still on my list, though.

**Comment by dzenanz** [comment]
Fixed by Microsoft/vcpkg#5115.

**Comment by floitsch** [comment]
aah. Thanks. Even better :)
