### ISSUE TITLE
Possibly incorrect downcasting of separator_

### ISSUE THREAD

**Issue by sffc** [google/double-conversion#89]
The template type `Iterator` is used throughout double-conversion.cpp.  It appears that `Iterator` can be one of two types:

- `const uc16*`
- `const char*`

There is a function `Advance` whose signature is:

```cpp
template<class Iterator>
static bool Advance (Iterator* it, char separator, int base, Iterator& end)
```

The call sites look like this:

```cpp
// current is of type Iterator
Advance(&current, separator_, 10, end)
```

The problem is that `separator_` is being downcast to a `char` even when using the `uc16*` template type for the string.  The implication is that there is a possible loss of information; for example, the separator might be a Unicode code point that doesn't fit in a char.  A great real-life example could be 'NARROW NO-BREAK SPACE' (U+202F), which is now used in CLDR as the default grouping separator in France.

The code should be checked to ensure that `separator_` is not downcast to a `char` unless the iterator is a `char` iterator.

**Comment by floitsch** [comment]
Will look into it.
Don't hesitate to ping from time to time (~ once a week?) to make sure I don't forget.

**Comment by sffc** [comment]
Thank you!
