### ISSUE TITLE
Wrong output fo StrToD16 v3.1.2

### ISSUE THREAD

**Issue by xmnlab** [google/double-conversion#90]
Hi everyone!

we are trying to update the double-conversion conda package to v3.1.2* but it is raising an error in the tests.

```
[100%] Linking CXX executable cctest
[100%] Built target cctest
$SRC_DIR/test/cctest/test-conversions.cc:3611:
 CHECK_EQ(3.0, StrToD16("0x0@23.p0", flags, 0.0, &processed, &all_used, char_separator, separator)) failed
#  Expected: 3.000000000000000000000000000000e+00
#  Found:    3.500000000000000000000000000000e+01
xargs: test/cctest/cctest: terminated by signal 6
```

any idea about what could be the problem? thanks!

* https://github.com/conda-forge/double-conversion-feedstock/pull/8

**Comment by floitsch** [comment]
That's on me.
I "fixed" separators over the weekend and broke something in the process. (I hope it's just the test).
Will look at it immediately.

**Comment by floitsch** [comment]
Fixed with 860b43156c1ba436aba9792407429bf46b9780a0.

No idea how this went through, but it fortunately was only a typo in the test.

**Comment by floitsch** [comment]
Just for the record, I have a pretty good idea of what happened now.
To ensure that the test was correctly run, I changed it to force an error. I then changed it back, but my C++ IDE doesn't automatically save on lost-focus, and I thus uploaded the code with the changed test.

**Comment by xmnlab** [comment]
Thanks @floitsch for the fix and the explanation.
