### ISSUE TITLE
fix headers includes in double conversion

### ISSUE THREAD

**Issue by Neumann-A** [google/double-conversion#91]
all double-conversion headers should be correctly included with `""` instead of `<>`

example:
`#include <double-conversion\utils.h>`
should be changed to
`#include "utils.h"`

you are generating build failures due to that using cmake....
also system includes are not meant to be used for internal headers... also your are vulnerable to including the wrong utils.h using system headers. 
Example:
Two folders: 
double-conversion
double-conversion_v2

double-conversion_v2 will include the headers from double-conversion instead of double-conversion_v2

**Comment by Neumann-A** [comment]
related to #85

**Comment by floitsch** [comment]
I agree that relative includes are better and just changed the code. Especially if it removes issues with the cmake build. (Thanks for connecting the two bugs).

The structure was inherited from v8's build conventions, so I hope I'm not breaking anything there...

**Comment by sffc** [comment]
+1

**Comment by ebarg666** [comment]
Apply

**Comment by ebarg666** [comment]
https://github.com/google/double-conversion/issues/91#issuecomment-583251207

**Comment by ebarg666** [comment]
Apply https://github.com/google/double-conversion/issues/91#issuecomment-583251207
