### ISSUE TITLE
Round-up will lead to overflow when the number is near upper-boundary

### ISSUE THREAD

**Issue by amanjiang** [google/double-conversion#95]
TEST(FooBar)
    {
        double f = 1.7976931348623157e308;

        const int kBufferSize = 128;

        char buffer[kBufferSize];

        StringBuilder builder(buffer, kBufferSize);

        DoubleToStringConverter dc(0, NULL, NULL, 'e', -4, 17, 0, 0);

        dc.ToExponential(f, 14, &builder);

        const char* str = builder.Finalize();

        StringToDoubleConverter sc(0, 0.0, 1.0, "inf", "nan");

        int count;

        double f2 = sc.StringToDouble(str, strlen(str), &count);

        CHECK(fabs(f - f2) < 1000.0);
    }

This may be extreme. When `requested_digits` is 14, the max value of double `1.7976931348623157e308` is rounded-up to `"1.79769313486232e308"`; If you read this string back to double, you will get an `inf` value.

**Comment by floitsch** [comment]
So, I guess it should just return infinity directly...
Will try to find the time to look at it this weekend.

**Comment by amanjiang** [comment]
I tested the dtoa.c of David M. Gay and it has this issue too, so I guess this may not be a problem.

**Comment by floitsch** [comment]
Ok. Thanks.
I will leave it as is then.
